language: php

php:
 - 5.4
 - 5.5
 - 5.6
 - 7.0
 - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache
env:
  global:
    # moved CUBRID related env variables because token needs to be secure
    - CUBRID_VERSION=9.3.0/CUBRID-9.3.0.0206
    - CUBRID_PDO_VERSION=9.3.0.0001
    - secure: secure_github_oauth_token_generated_with_travis

before_install:
  - composer config -g github-oauth.github.com "$GITHUB_TOKEN"
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction
  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
      # gmagick is not installed on travis currently
      #printf "\n" | pecl install gmagick
    fi
# setup application:
  - |
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" config/web.php

script:
  - |
    php -S localhost:8080 -t web > /dev/null 2>&1 &
    vendor/bin/codecept run